# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client_authwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Auth_widget(object):
    def setupUi(self, Auth_widget):
        Auth_widget.setObjectName("Auth_widget")
        Auth_widget.resize(203, 222)
        Auth_widget.setMinimumSize(QtCore.QSize(203, 222))
        Auth_widget.setMaximumSize(QtCore.QSize(203, 222))
        Auth_widget.setMouseTracking(False)
        self.textEdit = QtWidgets.QTextEdit(Auth_widget)
        self.textEdit.setGeometry(QtCore.QRect(10, 40, 181, 31))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(Auth_widget)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 110, 181, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label = QtWidgets.QLabel(Auth_widget)
        self.label.setGeometry(QtCore.QRect(10, 10, 181, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Auth_widget)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 181, 17))
        self.label_2.setObjectName("label_2")
        self.start_push_button = QtWidgets.QPushButton(Auth_widget)
        self.start_push_button.setGeometry(QtCore.QRect(8, 180, 91, 25))
        self.start_push_button.setShortcut("")
        self.start_push_button.setObjectName("start_push_button")
        self.cancel_push_button = QtWidgets.QPushButton(Auth_widget)
        self.cancel_push_button.setGeometry(QtCore.QRect(110, 180, 81, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel_push_button.sizePolicy().hasHeightForWidth())
        self.cancel_push_button.setSizePolicy(sizePolicy)
        self.cancel_push_button.setMaximumSize(QtCore.QSize(110, 180))
        self.cancel_push_button.setShortcut("")
        self.cancel_push_button.setObjectName("cancel_push_button")

        self.retranslateUi(Auth_widget)
        self.cancel_push_button.clicked.connect(Auth_widget.close) # type: ignore
        self.start_push_button.clicked.connect(Auth_widget.update) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Auth_widget)

    def retranslateUi(self, Auth_widget):
        _translate = QtCore.QCoreApplication.translate
        Auth_widget.setWindowTitle(_translate("Auth_widget", "Авторизация"))
        self.label.setText(_translate("Auth_widget", "Имя пользователя:"))
        self.label_2.setText(_translate("Auth_widget", "Пароль:"))
        self.start_push_button.setText(_translate("Auth_widget", "Старт!"))
        self.cancel_push_button.setText(_translate("Auth_widget", "Отмена"))
