# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'server_add_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QDialog
import sys


class UiServerAddUserForm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(308, 321)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed,
            QtWidgets.QSizePolicy.Fixed,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            Form.sizePolicy().hasHeightForWidth()
        )
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(308, 321))
        Form.setMaximumSize(QtCore.QSize(308, 321))
        Form.setMouseTracking(True)
        # 1. Кнопка регистрация
        self.register_button = QtWidgets.QPushButton(Form)
        self.register_button.setGeometry(QtCore.QRect(10, 280, 191, 25))
        self.register_button.setObjectName("register_button")
        # 2. Кнопка отмена
        self.cancel_button = QtWidgets.QPushButton(Form)
        self.cancel_button.setGeometry(QtCore.QRect(220, 280, 81, 25))
        self.cancel_button.setObjectName("cancel_button")
        # 3. Поле ввода имени пользователя
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(50, 50, 201, 25))
        self.lineEdit.setMaxLength(50)
        self.lineEdit.setObjectName("lineEdit")
        # 4. Поле ввода пароля
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 150, 201, 25))
        self.lineEdit_2.setMaxLength(100)
        self.lineEdit_2.setObjectName("lineEdit_2")
        # 5. Поле подтверждения пароля
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(50, 210, 201, 25))
        self.lineEdit_3.setMaxLength(100)
        self.lineEdit_3.setObjectName("lineEdit_3")
        # 6. Надпись над полем ввода имени пользователя
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 16, 201, 31))
        self.label.setObjectName("label")
        # 7. Надпись над полем ввода пароля
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(50, 106, 201, 31))
        self.label_2.setObjectName("label_2")
        # 8. Надпись над полем ввода подтверждения пароля
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(50, 180, 201, 31))
        self.label_3.setObjectName("label_3")
        # 9. Разделитель 1
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(10, 90, 291, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        # 10. Разделитель 2
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(10, 250, 291, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")

        self.retranslateUi(Form)
        self.cancel_button.clicked.connect(Form.close)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Регистрация пользователя"))
        self.register_button.setText(_translate("Form", "Регистрация"))
        self.cancel_button.setText(_translate("Form", "Отмена"))
        self.label.setText(_translate("Form", "Имя пользователя:"))
        self.label_2.setText(_translate("Form", "Пароль"))
        self.label_3.setText(_translate("Form", "Подтверждение пароля:"))


class ServerAddUser(QDialog):
    """Отображение окна добавления пользователя"""
    def __init__(self):
        super(ServerAddUser, self).__init__()
        self.ui = UiServerAddUserForm()
        self.ui.setupUi(self)
        self.show()


if __name__ == '__main__':
    app = QApplication(sys.argv)
    window = ServerAddUser()
    sys.exit(app.exec_())
