# -*- coding: utf-8 -*-
import sys

# Form implementation generated from reading ui file 'client_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow



class ClientWindowMain(QMainWindow):
    """Start main window for server part of messenger"""

    def __init__(self):
        super(ClientWindowMain, self).__init__()
        self.ui = UiClientMainWindowForm()
        self.ui.setupUi(self)
        self.show()


class UiClientMainWindowForm(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(557, 539)
        MainWindow.setAcceptDrops(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 141, 21))
        self.label.setObjectName("label")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(10, 40, 181, 281))
        self.listView.setObjectName("listView")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 10, 231, 21))
        self.label_2.setObjectName("label_2")
        self.listView_2 = QtWidgets.QListView(self.centralwidget)
        self.listView_2.setGeometry(QtCore.QRect(200, 40, 341, 281))
        self.listView_2.setObjectName("listView_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 330, 411, 31))
        self.label_3.setObjectName("label_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(200, 360, 341, 111))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(18, 370, 171, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(18, 410, 171, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 557, 22))
        self.menubar.setObjectName("menubar")
        self.menuExit = QtWidgets.QMenu(self.menubar)
        self.menuExit.setObjectName("menuExit")
        self.menuRefresh = QtWidgets.QMenu(self.menubar)
        self.menuRefresh.setObjectName("menuRefresh")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuExit.menuAction())
        self.menubar.addAction(self.menuRefresh.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Мессенджер. Клиент v 0.2.0"))
        self.label.setText(_translate("MainWindow", "Список контактов"))
        self.label_2.setText(_translate("MainWindow", "История сообщений"))
        self.label_3.setText(_translate("MainWindow", "Для выбора получателя кликните его в списке контактов"))
        self.pushButton.setText(_translate("MainWindow", "Добавить контакт"))
        self.pushButton_2.setText(_translate("MainWindow", "Удалить контакт"))
        self.menuExit.setTitle(_translate("MainWindow", "Файл"))
        self.menuRefresh.setTitle(_translate("MainWindow", "Контакты"))


if __name__ == '__main__':
    app = QApplication(sys.argv)
    application = ClientWindowMain()
    sys.exit(app.exec_())
